spring:
  profiles:
    active: actuator, console, config, ${PROFILE:test}
    #group:
      #prod:
      #test:
  application:
      name: stripe-integration

server:
  port: ${STRIPE_PORT:8000}
  forward-headers-strategy: framework