spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:vehicle}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
      maximum-pool-size: 10
      connection-timeout: 30000
      validation-timeout: 5000
      initialization-fail-timeout: -1 
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true

application:
  cors:
    allowed: "*"
    time: 3600
  page:
    size: 10
