spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVICE}
    producer:
      client-id: ${PRODUCER_ID}
      topic:
        name: ${KAFKA_TOPIC}
      partitions: ${KAFKA_PARTITIONS}
      replicas: ${KAFKA_REPLICAS}
  datasource: 
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: false