services:
  securityhash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stripe-automation
    restart: unless-stopped
    ports:
      - "${STRIPE_PORT}:${STRIPE_PORT}"
    env_file:
      - .env
