spring:
  output:
    ansi:
      enabled: always
  aop:
    auto: true # When you don't need logging.
  banner:
    location: classpath:banner/banner.txt
  main:
    banner-mode: console
logging:
  level:
    root: info
    org:
      springframework: warn
      boot: error
      data:
        redis: debug
  pattern:
    console: '%n %d{HH:mm:ss} | %highlight(%-5level) | %cyan(%logger{30}) | %msg'