spring:
  
  # Postgresql
  main:
    lazy-initialization: false
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    pool:
      initial-size: 20
      max-size: 100 
      max-idle-time: 30m
      max-create-connection-time: 5s
      max-acquire-time: 5s
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql
    
application:
  size:
    page: ${PAGE_SIZE:20}

