spring:
  profiles:
    active: actuator, console, config, prod # ${PROFILE:test}
    #group: 
      #prod: 
      #test: 
  application:
      name: Security-HASH

server:
  port: ${SECURITY_HASH:8000}
  forward-headers-strategy: framework