spring:
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    show-sql: false 
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  #flyway:
    #locations: classpath:db/migration
    #baseline-version: 1
    #baseline-on-migrate: true
    #clean-disabled: true
    #create-schemas: true
    #validate-on-migrate: true
    #lock-retry-count: 10
    #connect-retries: 3
    #connect-retries-interval: 30s

	
application:
  size:
    page: ${PAGE_SIZE:20}

settings:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
    max-age: ${CORS_TIME:3600}
