spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_LIBRARY:example} 
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      keepalive-time: 300000
  jpa:
    open-in-view: false 
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  elasticsearch:
    uris: ${ELASTIC_URI:http://localhost:9200}
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
    connection-timeout: 5000
    socket-timeout: 30000 
    socket-keep-alive: true

webflux:
  api:
    user: ${USER_PORT}