spring:
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    show-sql: false 
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  #flyway:
    #locations: classpath:db/migration
    #baseline-version: 1
    #baseline-on-migrate: true
    #clean-disabled: true
    #create-schemas: true
    #validate-on-migrate: true
    #lock-retry-count: 10
    #connect-retries: 3
    #connect-retries-interval: 30s
        
#scheduled:
  #token-cleanup: ${TOKEN_CLEANUP:24h}      

#cookies:
  #security:
    #cookie-name: _adaptative_stored_int_ # Refresh Token Cookie Name
    #same-site: "Lax"
    #secure: true

#cache:
  #chances:
    #max-attempts: ${LOGIN_ATTEMPTS:5}
  #time:
    #login-attempt: ${LOGIN_CACHE_TIME:15m}
  #name:
    #login-attempt: "login-attempt-cache"

#security:
  #https-only: ${HTTPS_ONLY:true} # Set on false when developing
  #front:
    #csrf: ${CSRF_ENABLED:true}
  #tokens:
    #secret-key: ${SECURITY_KEY} # Generate one when developing
    #expiration: ${EXPIRATION_KEY:15m}
    #refresh-token: ${REFRESH_KEY:7d}
    #types:
      #access-id: "ashudgquwguegq"
      #refresh-id: "hucvghasbhiodfiwer"

application:
  size:
    #file: ${FILE_SIZE:20} #MB
    page: ${PAGE_SIZE:20}
  #track:
    #time: ${TRACKVIEW_TIME:5d}
  #bucket:
    #max-time: ${BUCKET_MAXTIME:20m}

#storage:
  #allowed-types: image/jpg, image/jpeg, image/png, image/webp, application/pdf
  #folder:
    #name: ${STORAGE_FOLDER_NAME:images}

  #bucket:
    #endpoint: ${BUCKET_ENDPOINT:NONE}
    #access-key-id: ${BUCKET_ACCESS_KEY:NONE}
    #secret-access-key: ${BUCKET_SECRET_KEY:NONE}
    #bucket-name: ${BUCKET_NAME:NONE}
    #region: ${BUCKET_REGION:NONE}
    #ddlAuto: ${BUCKET_DDL_AUTO:update}
    #accelerate-enabled: ${BUCKET_ACCELERATE:false}
    #s3:
      #path-style-access-enabled: true

settings:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
    max-age: ${CORS_TIME:3600}
  #security:
    #user: ${ADMIN_USER}
    #email: ${ADMIN_EMAIL}
    #password: ${ADMIN_PASSWORD}
